var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,a){if(b==Array.prototype||b==Object.prototype)return b;b[c]=a.value;return b};
$jscomp.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<b.length;++c){var a=b[c];if(a&&a.Math==Math)return a}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(b,c){var a=$jscomp.propertyToPolyfillSymbol[c];if(null==a)return b[c];a=b[a];return void 0!==a?a:b[c]};$jscomp.polyfill=function(b,c,a,d){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(b,c,a,d):$jscomp.polyfillUnisolated(b,c,a,d))};
$jscomp.polyfillUnisolated=function(b,c,a,d){a=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var e=b[d];if(!(e in a))return;a=a[e]}b=b[b.length-1];d=a[b];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(a,b,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(b,c,a,d){var e=b.split(".");b=1===e.length;d=e[0];d=!b&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];a=$jscomp.IS_SYMBOL_NATIVE&&"es6"===a?d[e]:null;c=c(a);null!=c&&(b?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:c}):c!==a&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):
$jscomp.POLYFILL_PREFIX+e),e=$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:c})))};$jscomp.polyfill("Object.is",function(b){return b?b:function(c,a){return c===a?0!==c||1/c===1/a:c!==c&&a!==a}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(b){return b?b:function(c,a){var d=this;d instanceof String&&(d=String(d));var e=d.length;a=a||0;for(0>a&&(a=Math.max(a+e,0));a<e;a++){var f=d[a];if(f===c||Object.is(f,c))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(b,c,a){if(null==b)throw new TypeError("The 'this' value for String.prototype."+a+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+a+" must not be a regular expression");return b+""};$jscomp.polyfill("String.prototype.includes",function(b){return b?b:function(c,a){return-1!==$jscomp.checkStringArgs(this,c,"includes").indexOf(c,a||0)}},"es6","es3");
function genericOnClick(b,c){chrome.storage.local.get(["resume"],function(a){"undefined"!==typeof a&&"undefined"!==typeof a.resume||createTab()})}function createTab(){chrome.windows.getCurrent(function(b){var c=chrome.extension.getURL("index.html");b={index:0,windowId:b.id,url:c,selected:!0};try{chrome.tabs.create(b)}catch(a){alert(a)}})}
function sendResume(){var b="";chrome.storage.local.get(["applyUserId"],function(c){b=c.applyUserId});chrome.storage.local.get(["resume"],function(c){sendData(JSON.stringify({userId:b,resume:c.resume}))})}function sendApplication(){}
chrome.runtime.onInstalled.addListener(function(){chrome.contextMenus.create({title:"Kumquat",id:"parent"});chrome.contextMenus.create({title:"Profile",parentId:"parent",id:"Profile"});generateUserId();chrome.runtime.onMessage.addListener(function(b,c,a){b.MESSEGE_TYPE===RESUME_MES?sendResume():b.MESSEGE_TYPE===JOB_URL_MES?sendData(c.tab.url):b.MESSEGE_TYPE===APPLICATION_MES&&sendApplication()})});
function randomstring(b){for(var c="";c.length<b;){var a=Math.floor(62*Math.random());a=10>a?a:36>a?String.fromCharCode(a+55):String.fromCharCode(a+61);c+=a}return c}function generateUserId(){var b=randomstring(16),c={};c[USER_ID]=b;chrome.storage.sync.set(c,function(){});c={};b=(c[USER_ID]=b,c);sendData(USER_ID,b)}
function sendData(b,c){var a=new XMLHttpRequest;a.open("POST",WEBURL+"/"+b,!0);a.onload=function(){};a.setRequestHeader("Content-Type","application/json; charset=UTF-8");b=JSON.stringify(c);a.send(b)}function sendUrl(b){var c="";chrome.storage.sync.get(USER_ID,function(a){c=a[USER_ID];a={};a=(a[USER_ID]=c,a[JOB_URL_MES]=b,a);sendData(JOB_URL_MES,a)})}
chrome.runtime.onInstalled.addListener(function(){chrome.contextMenus.onClicked.addListener(genericOnClick);chrome.tabs.onUpdated.addListener(function(b,c,a){"complete"===c.status&&"undefined"!==a.url&&"chrome://newtab/"!==a.url&&(a.url.includes("lever.co")||a.url.includes("taleo")||a.url.includes("myworkdayjobs")||a.url.includes("greenhouse"))&&sendUrl(a.url)});generateUserId();chrome.runtime.onMessage.addListener(function(b,c,a){b.MESSEGE_TYPE===RESUME_MES?sendResume():b.MESSEGE_TYPE===JOB_URL_MES?
sendData(c.tab.url):b.MESSEGE_TYPE===APPLICATION_MES&&sendApplication()})});chrome.runtime.onMessage.addListener(function(b){"notification"===b.type&&chrome.notifications.create("",b.options)});
