var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};
$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var f=a[e];if(!(f in c))return;c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var f=a.split(".");a=1===f.length;e=f[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var h=0;h<f.length-1;h++){var d=f[h];if(!(d in e))return;e=e[d]}f=f[f.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[f]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[f]&&($jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(f):
$jscomp.POLYFILL_PREFIX+f),f=$jscomp.propertyToPolyfillSymbol[f],$jscomp.defineProperty(e,f,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(b,c){var e=this;e instanceof String&&(e=String(e));var f=e.length;c=c||0;for(0>c&&(c=Math.max(c+f,0));c<f;c++){var h=e[c];if(h===b||Object.is(h,b))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,c||0)}},"es6","es3");
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(d){return d instanceof f?d:new f(function(g,k){g(d)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(d){if(null==this.batch_){this.batch_=[];var g=this;this.asyncExecuteFunction(function(){g.executeBatch_()})}this.batch_.push(d)};
var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(d){e(d,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=this.batch_;this.batch_=[];for(var g=0;g<d.length;++g){var k=d[g];d[g]=null;try{k()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var f=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var g=this.createResolveAndReject_();
try{d(g.resolve,g.reject)}catch(k){g.reject(k)}};f.prototype.createResolveAndReject_=function(){function d(l){return function(m){k||(k=!0,l.call(g,m))}}var g=this,k=!1;return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};f.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof f)this.settleSameAsPromise_(d);else{a:switch(typeof d){case "object":var g=null!=d;break a;case "function":g=!0;break a;default:g=!1}g?this.resolveToNonPromiseObj_(d):
this.fulfill_(d)}};f.prototype.resolveToNonPromiseObj_=function(d){var g=void 0;try{g=d.then}catch(k){this.reject_(k);return}"function"==typeof g?this.settleSameAsThenable_(g,d):this.fulfill_(d)};f.prototype.reject_=function(d){this.settle_(2,d)};f.prototype.fulfill_=function(d){this.settle_(1,d)};f.prototype.settle_=function(d,g){if(0!=this.state_)throw Error("Cannot settle("+d+", "+g+"): Promise already settled in state"+this.state_);this.state_=d;this.result_=g;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};f.prototype.scheduleUnhandledRejectionCheck_=function(){var d=this;e(function(){if(d.notifyUnhandledRejection_()){var g=$jscomp.global.console;"undefined"!==typeof g&&g.error(d.result_)}},1)};f.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var d=$jscomp.global.CustomEvent,g=$jscomp.global.Event,k=$jscomp.global.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof d?d=new d("unhandledrejection",{cancelable:!0}):
"function"===typeof g?d=new g("unhandledrejection",{cancelable:!0}):(d=$jscomp.global.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.result_;return k(d)};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=0;d<this.onSettledCallbacks_.length;++d)h.asyncExecute(this.onSettledCallbacks_[d]);this.onSettledCallbacks_=null}};var h=new b;f.prototype.settleSameAsPromise_=function(d){var g=this.createResolveAndReject_();
d.callWhenSettled_(g.resolve,g.reject)};f.prototype.settleSameAsThenable_=function(d,g){var k=this.createResolveAndReject_();try{d.call(g,k.resolve,k.reject)}catch(l){k.reject(l)}};f.prototype.then=function(d,g){function k(n,p){return"function"==typeof n?function(q){try{l(n(q))}catch(r){m(r)}}:p}var l,m,t=new f(function(n,p){l=n;m=p});this.callWhenSettled_(k(d,l),k(g,m));return t};f.prototype.catch=function(d){return this.then(void 0,d)};f.prototype.callWhenSettled_=function(d,g){function k(){switch(l.state_){case 1:d(l.result_);
break;case 2:g(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?h.asyncExecute(k):this.onSettledCallbacks_.push(k);this.isRejectionHandled_=!0};f.resolve=c;f.reject=function(d){return new f(function(g,k){k(d)})};f.race=function(d){return new f(function(g,k){for(var l=$jscomp.makeIterator(d),m=l.next();!m.done;m=l.next())c(m.value).callWhenSettled_(g,k)})};f.all=function(d){var g=$jscomp.makeIterator(d),k=g.next();return k.done?c([]):new f(function(l,
m){function t(q){return function(r){n[q]=r;p--;0==p&&l(n)}}var n=[],p=0;do n.push(void 0),p++,c(k.value).callWhenSettled_(t(n.length-1),m),k=g.next();while(!k.done)})};return f},"es6","es3");
$jscomp.polyfill("Array.from",function(a){return a?a:function(b,c,e){c=null!=c?c:function(g){return g};var f=[],h="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof h){b=h.call(b);for(var d=0;!(h=b.next()).done;)f.push(c.call(e,h.value,d++))}else for(h=b.length,d=0;d<h;d++)f.push(c.call(e,b[d],d));return f}},"es6","es3");var isWorkdayload=!1,taleoflag=!1;
function createPopup(a){var b=document.createElement("DIV");b.id="kumquatOverlay";document.body.insertBefore(b,document.body.firstChild);var c=document.createElement("IMG");c.id="kumquatTree";c.src=chrome.extension.getURL("kumquat_tree.png");var e=document.createElement("DIV");e.id="popupText";e.innerHTML="Kumquat Compatible!";var f=document.createElement("BUTTON");f.id="kumquatButton";f.innerHTML="Autofill Application";var h=document.createElement("DIV");h.id="popupClose";h.innerHTML="Try Later";
b.appendChild(c);b.appendChild(e);b.appendChild(f);b.appendChild(h);h.onclick=function(){b.remove()};f.onclick=function(){b.remove();chrome.storage.local.get("profile",function(d){if("undefined"==typeof d.profile)alert("You must save your Kumquat profile before autofilling.");else switch(PROFILE=JSON.parse(d.profile),a){case "workday":return workday();case "taleo":return taleo();case "greenhouse":return greenhouse();case "lever":return lever()}})}}
window.addEventListener("load",function(){isWorkdayload=!1;var a=window.location.toString();existsquery("input[id='first_name']")&&createPopup("greenhouse");window.location.toString().includes("myworkdayjobs")&&createPopup("workday");window.location.toString().includes("taleo")&&0==taleoflag&&createPopup("taleo");a.includes("lever.co")&&a.includes("/apply")&&createPopup("lever")});
chrome.runtime.onMessage.addListener(function(a,b){isWorkdayload=!1;var c=window.location.toString();chrome.storage.local.get("profile",function(e){"undefined"==typeof e.profile?alert("You must save your Kumquat profile before autofilling."):(PROFILE=JSON.parse(e.profile),existsquery("input[id='first_name']")&&greenhouse(),window.location.toString().includes("myworkdayjobs")&&workday(),window.location.toString().includes("taleo")&&0==taleoflag&&taleo(),c.includes("lever.co")&&c.includes("/apply")&&
lever())})});function completeNotification(){chrome.runtime.sendMessage("",{type:"notification",options:{title:"Autofill Complete!",message:"Thanks for using Kumquat.",iconUrl:"/kumquat48.png",type:"basic"}})};function existselementid(a){return document.getElementById(a)?!0:!1}function existsclass(a){return 0<document.getElementsByClassName(a).length?!0:!1}function existstag(a){return 0<document.getElementsByTagName(a).length?!0:!1}function existsquery(a){return document.querySelector(a)?!0:!1}function existsxpath(a){if(0<document.evaluate(a,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength)return!0}function trytype(a,b){existsquery(a)&&(document.querySelector(a).value=b)}
function moveclick(a){a=document.querySelector(a);a.scrollIntoView();a.click()}function waitForElement(a){return new Promise(function(b,c){if(c=document.querySelector(a))b(c);else{var e=new MutationObserver(function(f){f.forEach(function(h){h=Array.from(h.addedNodes);h=$jscomp.makeIterator(h);for(var d=h.next();!d.done;d=h.next())if(d=d.value,d.matches&&d.matches(a)){e.disconnect();b(d);break}})});e.observe(document.documentElement,{childList:!0,subtree:!0})}})}
function waitForXPath(a){return new Promise(function(b,c){if(c=document.evaluate(a,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0))b(c);else{var e=new MutationObserver(function(f){f.forEach(function(h){h=Array.from(h.addedNodes);h=$jscomp.makeIterator(h);for(var d=h.next();!d.done;d=h.next())if(d=d.value,d.matches&&d==document.evaluate(a,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0)){e.disconnect();b(d);break}})});e.observe(document.documentElement,
{childList:!0,subtree:!0})}})}function setSelectBoxByText(a,b){a=document.getElementById(a);for(var c=0;c<a.options.length;++c)a.options[c].text===b&&(a.options[c].selected=!0)};var inputevent=new Event("input",{bubbles:!0,cancelable:!0}),inputevent2=new Event("input",{bubbles:!0,cancelable:!1}),textinputevent=new Event("textInput",{bubbles:!0,cancelable:!0}),keydownevent=new Event("keydown",{bubbles:!0}),selectevent=new Event("select",{bubbles:!0,cancelable:!1});function changevalue(a,b){a.value=b;a.dispatchEvent(inputevent)}
function trytypexpath(a,b){if(ele=document.evaluate(a,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0))ele.value=b,ele.dispatchEvent(changeevent)}function trytypeworkday(a,b){document.querySelector(a)&&(a=document.querySelector(a),a.value=b,a.dispatchEvent(changeevent))}function trytypelist(a,b,c){if(a=document.evaluate(a,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(b))a.value=c,a.dispatchEvent(changeevent)}
function dropdownSelect(a,b){document.evaluate(a,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click();waitForXPath(b).then(function(){document.evaluate(b,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click()})}function setReactInputValue(a,b){if(a=document.querySelector(a))a.value=b,a.dispatchEvent(new Event("blur"))}
function reactTypeList(a,b,c){if(a=document.evaluate(a,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(b))a.value=c,a.dispatchEvent(new Event("blur"))}
function workdayLogin(){var a=document.querySelector("input[data-automation-id='email']"),b=document.querySelector("input[data-automation-id='password']");existsquery("input[data-automation-id=email]")||(a=document.querySelector("input[aria-label='Email Address']"),b=document.querySelector("input[aria-label='Password']"));changevalue(a,PROFILE.email);changevalue(b,PROFILE.password);setTimeout(function(){document.querySelector('div[data-automation-id="click_filter"]').click()},1E3)}
function workdayRegister(){var a="none";a=existsquery("input[data-automation-id='email']")?"modern":"archaic";"modern"==a&&(existsquery("[data-automation-id=email")&&changevalue(document.querySelector('[data-automation-id="email"]'),PROFILE.email),existsquery('[data-automation-id="userName"]')&&changevalue(document.querySelector('[data-automation-id="userName"]'),PROFILE.email),changevalue(document.querySelector('[data-automation-id="password"]'),PROFILE.password),existsquery("[data-automation-id=verifyPassword]")&&
changevalue(document.querySelector('[data-automation-id="verifyPassword"]'),PROFILE.password),existsquery('[data-automation-id="confirmPassword"]')&&changevalue(document.querySelector('[data-automation-id="confirmPassword"]'),PROFILE.password),existsquery('[data-automation-id="createAccountCheckbox"]')&&document.querySelector('[data-automation-id="createAccountCheckbox"]').click(),document.querySelector('[data-automation-id="click_filter"]').click(),completeNotification());"archaic"==a&&setTimeout(function(){existsquery('[aria-label="Email Address"]')&&
changevalue(document.querySelector('[aria-label="Email Address"]'),PROFILE.email);changevalue(document.querySelector('[aria-label="Password"]'),PROFILE.password);existsquery('[aria-label="Verify New Password"]')&&changevalue(document.querySelector('[aria-label="Verify New Password"]'),PROFILE.password);existsquery('[data-automation-id="checkboxPanel"]')&&document.querySelector('[data-automation-id="checkboxPanel"]').click();document.querySelector('[data-automation-id="click_filter"]').click();completeNotification()},
300)}
function workdayPersonalinfo(a,b,c){function e(){document.evaluate('//div[contains(text(), "'+PROFILE.state+'")]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click()}"default"==b&&(setReactInputValue('[data-automation-id="legalNameSection_firstName"]',PROFILE.first_name),setReactInputValue('[data-automation-id="legalNameSection_lastName"]',PROFILE.last_name),setReactInputValue('[data-automation-id="legalNameSection_primary"]',PROFILE.last_name),setReactInputValue('[data-automation-id="addressSection_addressLine1"]',PROFILE.street_address),
setReactInputValue('[data-automation-id="addressSection_city"]',PROFILE.city),setReactInputValue('[data-automation-id="addressSection_postalCode"]',PROFILE.zip_code),setReactInputValue('[data-automation-id="phone-number"]',PROFILE.phone),document.evaluate('//label[contains(text(), "State")]//following::button[1]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click(),waitForXPath('//div[contains(text(), "California")]').then(e()),completeNotification());if("custom"==b){trytypexpath('//*[contains(text(), "First Name")]//following::input[1]',
PROFILE.first_name);trytypexpath('//*[contains(text(), "Last Name")]//following::input[1]',PROFILE.last_name);b=document.evaluate('//label[contains(text(), "State")]//following::div[2]//div[1]//div[1]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0);trytypexpath("//*[contains(text(), 'Address Line 1')]//following::input[1]",PROFILE.street_address);trytypexpath("//*[contains(text(), 'City')]//following::input[1]",PROFILE.city);trytypexpath("//*[contains(text(), 'Postal Code')]//following::input[1]",
PROFILE.zip_code);var f=document.evaluate("//*[contains(text(), 'Phone Number')]//following::input[1]",document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(1);f.value=PROFILE.phone;f.dispatchEvent(changeevent);b.click();waitForXPath('//div[contains(text(), "'+PROFILE.state+'")]').then(e());completeNotification()}c.addEventListener("click",function(){setTimeout(function(){1==a?waitForXPath('//*[@data-automation-id="taskOrchCurrentItemLabel"]').then(createPopup("workday")):2==a?waitForElement("[class=css-1uso8fp]").then(createPopup("workday")):
3==a&&waitForElement("h2").then(createPopup("workday"))},3E3)})}
function workdayExperience(a,b){var c=1,e=document.getElementsByTagName("body")[0].innerText;if("default"==b&&0==e.includes("Job Title")){var f=function(){setReactInputValue('[data-automation-id="jobTitle"]',PROFILE.job_title1);setReactInputValue('[data-automation-id="company"]',PROFILE.employer1);setReactInputValue('[data-automation-id="location"]',PROFILE.job_location1);setReactInputValue('[data-automation-id="description"]',PROFILE.job_desc1);reactTypeList('//*[contains(text(), "Work Experience")]//following::*[@data-automation-id="dateInputWrapper"]',
0,PROFILE.job_start_month1+PROFILE.job_start_year1);1==PROFILE.current_job1?document.querySelector('[data-automation-id="currentlyWorkHere"]').click():(reactTypeList('//*[@data-automation-id="dateInputWrapper"]',c,PROFILE.job_end_month1+PROFILE.job_end_year1),c+=1);""!=PROFILE.employer2&&waitForXPath('//*[@aria-label="Add Another Work Experience"]').then(function(){document.querySelector('[aria-label="Add Another Work Experience"]').click();setTimeout(function(){reactTypeList('//*[@data-automation-id="jobTitle"]',
1,PROFILE.job_title2);reactTypeList('//*[@data-automation-id="company"]',1,PROFILE.employer2);reactTypeList('//*[@data-automation-id="location"]',1,PROFILE.job_location2);reactTypeList('//*[@data-automation-id="description"]',1,PROFILE.job_desc2);reactTypeList('//*[@data-automation-id="dateInputWrapper"]',c,PROFILE.job_start_month2+PROFILE.job_start_year2);c+=1;1==PROFILE.current_job2?document.evaluate('//*[@data-automation-id="currentlyWorkHere"]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
null).snapshotItem(1).click():(reactTypeList('//*[@data-automation-id="dateInputWrapper"]',c,PROFILE.job_end_month2+PROFILE.job_end_year2),c+=1);""!=PROFILE.employer3&&waitForElement('[aria-label="Add Another Work Experience"]').then(function(){document.querySelector('[aria-label="Add Another Work Experience"]').click();setTimeout(function(){reactTypeList('//*[@data-automation-id="jobTitle"]',2,PROFILE.job_title3);reactTypeList('//*[@data-automation-id="company"]',2,PROFILE.employer3);reactTypeList('//*[@data-automation-id="location"]',
2,PROFILE.job_location3);reactTypeList('//*[@data-automation-id="description"]',2,PROFILE.job_desc3);reactTypeList('//*[@data-automation-id="dateInputWrapper"]',c,PROFILE.job_start_month3+PROFILE.job_start_year3);c+=1;1==PROFILE.current_job3?document.evaluate('//*[@data-automation-id="currentlyWorkHere"]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(2).click():(reactTypeList('//*[@data-automation-id="dateInputWrapper"]',c,PROFILE.job_end_month3+PROFILE.job_end_year3),c+=
1)},2E3)})},2E3)});(e.includes("Degree")||document.querySelector('[aria-label="Add Education"]'))&&0==e.includes("Degree")&&(document.querySelector("[aria-label='Add Education']").click(),setTimeout(function(){setReactInputValue("[data-automation-id='school']",PROFILE.university);setReactInputValue("[data-automation-id='gpa']",PROFILE.gpa);reactTypeList('//*[@data-automation-id="educationSection"]//*[@data-automation-id="dateInputWrapper"]',0,PROFILE.uni_start_year);reactTypeList('//*[@data-automation-id="educationSection"]//*[@data-automation-id="dateInputWrapper"]',
1,PROFILE.grad_year);document.querySelector("[data-automation-id='degree']").click();setTimeout(document.evaluate('//div[contains(text(), "Bachelors Degree")]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click(),800)},2E3));(existsquery('[aria-label="Add Languages"]')||e.includes("native language"))&&0==e.includes("native language")&&(document.querySelector("[aria-label='Add Languages']").click(),setTimeout(function(){document.querySelector("[data-automation-id='language']").click();
setTimeout(document.evaluate('//div[contains(text(), "English")]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click(),500)},1E3),setTimeout(function(){document.querySelector("[data-automation-id='languageProficiency-0']").click();setTimeout(document.evaluate('//div[contains(text(), "Native")]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click(),1500)},2E3),setTimeout(function(){document.querySelector('[data-automation-id="nativeLanguage"]').click();
completeNotification()},2400))};document.querySelector("[aria-label='Add Work Experience']").click();setTimeout(function(){f()},2E3)}"custom"==b&&(0==e.includes("Job Title")&&document.evaluate('//*[contains(text(), "Work Experience")]//following::button[1]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click(),waitForXPath('//*[contains(text(), "Job Title")]//following::input[1]').then(function(){setTimeout(function(){trytypexpath('//*[contains(text(), "Job Title")]//following::input[1]',
PROFILE.job_title1);trytypexpath('//*[contains(text(), "Company")]//following::input[1]',PROFILE.employer1);trytypexpath('//*[contains(text(), "Location")]//following::input[1]',PROFILE.job_location1);trytypexpath('//*[contains(text(), "Role Description")]//following::textarea[1]',PROFILE.job_desc1);job1input=document.evaluate('//*[contains(text(), "Work Experience")]//following::*[@data-automation-id="dateWidgetInputBox"]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0);
var h=document.evaluate('//*[contains(text(), "Work Experience")]//following::*[@data-automation-id="dateSectionMonth"]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0);job1input.dispatchEvent(selectevent);h.setAttribute("aria-valuenow",PROFILE.grad_month);h.innerText=PROFILE.grad_month;job1input.dispatchEvent(inputevent2);h=document.evaluate('//*[contains(text(), "Work Experience")]//following::*[@data-automation-id="dateSectionYear"]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
null).snapshotItem(0);h.setAttribute("aria-valuenow",PROFILE.job_start_year1);h.innerText=PROFILE.job_start_year1;job1input.dispatchEvent(inputevent2);job1input.dispatchEvent(changeevent);1==PROFILE.current_job1?document.evaluate('(//label[contains(text(), "currently work here")])[1]//following::input[1]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click():(trytypelist('//*[contains(text(), "Work Experience")]//following::*[@data-automation-id="dateWidgetInputBox"]',
c,PROFILE.job_end_month1+PROFILE.job_end_year1),c+=1)},1E3);""!=PROFILE.employer2&&setTimeout(function(){document.evaluate('//*[contains(text(), "Work Experience")]//following::button[2]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click();setTimeout(function(){trytypexpath('(//*[contains(text(), "Job Title")])[3]//following::input[1]',PROFILE.job_title2);trytypexpath('(//*[contains(text(), "Location")])[3]//following::input[1]',PROFILE.job_location2);trytypexpath('(//*[contains(text(), "Company")])[3]//following::input[1]',
PROFILE.employer2);trytypexpath('(//*[contains(text(), "Role Description")])[3]//following::textarea[1]',PROFILE.job_desc2);trytypelist('//*[contains(text(), "Work Experience")]//following::*[@data-automation-id="dateWidgetInputBox"]',c,PROFILE.job_start_month2+PROFILE.job_start_year2);c+=1;1==PROFILE.current_job2?document.evaluate('(//label[contains(text(), "currently work here")])[2]//following::input[1]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click():(trytypelist('//*[contains(text(), "Work Experience")]//following::*[@data-automation-id="dateWidgetInputBox"]',
c,PROFILE.job_end_month2+PROFILE.job_end_year2),c+=1);waitForXPath('//*[contains(text(), "Work Experience")]//following::button[3]').then(function(){document.evaluate('//*[contains(text(), "Work Experience")]//following::button[3]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click();setTimeout(function(){trytypexpath('(//*[contains(text(), "Job Title")])[last()]//following::input[1]',PROFILE.job_title3);trytypexpath('(//*[contains(text(), "Company")])[last()]//following::input[1]',
PROFILE.employer3);trytypexpath('(//*[contains(text(), "Location")])[last()]//following::input[1]',PROFILE.job_location3);trytypexpath('(//*[contains(text(), "Role Description")])[last()]//following::textarea[1]',PROFILE.job_desc3);trytypelist('//*[contains(text(), "Work Experience")]//following::*[@data-automation-id="dateWidgetInputBox"]',c,PROFILE.job_start_month3+PROFILE.job_start_year3);c+=1;1==PROFILE.current_job3?document.evaluate('(//label[contains(text(), "currently work here")])[3]//following::input[1]',
document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click():(trytypelist('//*[contains(text(), "Work Experience")]//following::*[@data-automation-id="dateWidgetInputBox"]',c,PROFILE.job_end_month3+PROFILE.job_end_year3),c+=1)},800)})},1E3)},2E3);if(e.includes("Degree")||existsxpath('//*[contains(text(), "Education")]//following::button[1]'))0==e.includes("Degree")&&document.evaluate('//*[contains(text(), "Education")]//following::button[1]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
null).snapshotItem(0).click(),setTimeout(function(){trytypexpath('(//*[contains(text(), "University")])//following::input[1]',PROFILE.university);dropdownSelect('//*[contains(text(), "Degree")]//following::*[@data-automation-id="selectWidget"][1]','//*[@data-automation-label="'+PROFILE.degree+'"]');trytypexpath('(//*[contains(text(), "Overall Result")])//following::input[1]',PROFILE.gpa);trytypelist('//*[contains(text(), "Education")]//following::*[@data-automation-id="dateWidgetInputBox"]',0,PROFILE.uni_start_year);
trytypelist('//*[contains(text(), "Education")]//following::*[@data-automation-id="dateWidgetInputBox"]',1,PROFILE.grad_year)},1200);if(e.includes("native language")||existsxpath('//*[contains(text(), "Languages")]//following::button[1]'))0==e.includes("native language")&&document.evaluate('//*[contains(text(), "Languages")]//following::button[1]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click(),setTimeout(function(){document.evaluate('(//label[contains(text(), "native language")])//following::div[@data-automation-id="checkboxPanel"][1]',
document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click();completeNotification()},6E3)}()))}
function workday(a,b,c){var e=document.getElementsByTagName("body")[0].innerText.toLowerCase();if(existsxpath('//button[contains(text(), "Create Account")]'))return workdayRegister();if(e.includes("sign in"))return workdayLogin();e="none";if(existsquery('[data-automation-id="taskOrchCurrentItemLabel"]')){a=1;var f=document.evaluate('//*[@data-automation-id="taskOrchCurrentItemLabel"]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0);e=document.evaluate('//*[@data-automation-id="taskOrchCurrentItemLabel"]',
document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).innerText}else existsclass("css-1uso8fp")?(a=2,f=document.getElementsByClassName("css-1uso8fp")[0],e=document.getElementsByClassName("css-1uso8fp")[0].innerText):existstag("h2")&&(a=3,f=document.getElementsByTagName("h2")[0],e=document.getElementsByTagName("h2")[0].innerText);e=e.toLowerCase();existsquery("[data-automation-id='bottom-navigation-next-button']")?(b="default",c=document.querySelector("[data-automation-id='bottom-navigation-next-button']")):
existsquery('[data-automation-id="wd-CommandButton_next"]')&&(b="custom",c=document.querySelector('[data-automation-id="wd-CommandButton_next"]'));if(e.includes("my information"))return workdayPersonalinfo(a,b,c);if(e.includes("my experience"))return workdayExperience(a,b);c.addEventListener("click",function(){setTimeout(function(){if(f)return workday(a,b,c)},7E3)})};var changeevent=new Event("change",{bubbles:!0});function tryvalue(a,b){document.getElementById(a)&&(document.getElementById(a).value=b)}function dateselect(a,b){var c=document.getElementById(a);document.getElementById(a)&&(c.value=b,c.dispatchEvent(inputevent2),c.dispatchEvent(changeevent))}
function taleoLogin(){document.getElementById("dialogTemplate-dialogForm-login-name1").value=PROFILE.username;document.getElementById("dialogTemplate-dialogForm-login-password").value=PROFILE.password;document.getElementById("dialogTemplate-dialogForm-login-defaultCmd").click();setTimeout(function(){document.getElementById("dialogTemplate-dialogForm-login-errorMessageTitle")&&(document.getElementById("dialogTemplate-dialogForm-login-register").click(),waitForElement("[id=dialogTemplate-dialogForm-userName]").then(function(){document.getElementById("dialogTemplate-dialogForm-userName").value=
PROFILE.username;document.getElementById("dialogTemplate-dialogForm-password").value=PROFILE.password;document.getElementById("dialogTemplate-dialogForm-passwordConfirm")&&(document.getElementById("dialogTemplate-dialogForm-passwordConfirm").value=PROFILE.password);document.getElementById("dialogTemplate-dialogForm-email").value=PROFILE.email;setTimeout(function(){document.getElementById("dialogTemplate-dialogForm-defaultCmd").click()},1E3)}))},2E3)}
function taleoRegister(){waitForElement("[id='dialogTemplate-dialogForm-userName']").then(function(){document.getElementById("dialogTemplate-dialogForm-userName").value=PROFILE.username;document.getElementById("dialogTemplate-dialogForm-password").value=PROFILE.password;document.getElementById("dialogTemplate-dialogForm-passwordConfirm")&&(document.getElementById("dialogTemplate-dialogForm-passwordConfirm").value=PROFILE.password);document.getElementById("dialogTemplate-dialogForm-email").value=PROFILE.email;
setTimeout(function(){document.getElementById("dialogTemplate-dialogForm-defaultCmd").click()},1E3)})}function taleoSecurity(){waitForElement("[id='dialogTemplate-dialogForm-j_id_id18pc6-0-question']").then(function(){document.getElementById("dialogTemplate-dialogForm-j_id_id18pc6-0-question").value=PROFILE.question;document.getElementById("dialogTemplate-dialogForm-j_id_id18pc6-0-answer").value=PROFILE.answer})}
function taleoPersonalinfo(){var a=0;document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_1-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_FirstName")&&(a=1);document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_2-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_FirstName")&&(a=2);document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_FirstName").value=PROFILE.first_name;document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+
a+"-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_LastName").value=PROFILE.last_name;document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_Address").value=PROFILE.street_address;document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_City").value=PROFILE.city;document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_ZipCode").value=
PROFILE.zip_code;var b=document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_MobilePhone"),c=document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_HomePhone");document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_PreferredPhone")&&(document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_PreferredPhone").value=
1);c?c.value=PROFILE.phone:b&&(b.value=PROFILE.phone);b=document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_ResidenceLocation-0");b.value=document.evaluate('//*[@id="et-ef-content-ftf-gp-j_id_id16pc9-page_'+a+'-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_ResidenceLocation-0"]//option[contains(text(), "United States")]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).value;b.dispatchEvent(inputevent2);b.dispatchEvent(changeevent);
setTimeout(function(){var e=document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_ResidenceLocation-1");e.value=document.evaluate('//*[@id="et-ef-content-ftf-gp-j_id_id16pc9-page_'+a+'-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_ResidenceLocation-1"]//option[contains(text(), "'+PROFILE.state+'")]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).value;e.dispatchEvent(inputevent2);e.dispatchEvent(changeevent);
setTimeout(function(){completeNotification()},1900)},800)}
function taleoExperience(){taleoflag=!0;var a="0",b="0";document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_1-we-wei-0-frm-dv_cs_experience_Employer")?(a="1",b=document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_0-csef-efi-0-frm-dv_cs_education_Program")?"0":"2"):document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_2-we-wei-0-frm-dv_cs_experience_Employer")?(a="2",b=document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_1-csef-efi-0-frm-dv_cs_education_Program")?"1":
"0"):b=document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_1-csef-efi-0-frm-dv_cs_education_Program")?"1":"2";""!=PROFILE.employer2&&null==document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-1-frm-dv_cs_experience_Employer")&&alert("Due to page restrictions you may have to click autofill multiple times after each autofill complete notification for your multiple previous work experiences.");document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-0-frm-dv_cs_experience_Employer").value=
PROFILE.employer1;tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-0-frm-dv_cs_experience_Responsibility",PROFILE.job_desc1);tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-0-frm-dv_cs_experience_JobFunction",PROFILE.job_title1);tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-0-frm-dv_cs_experience_UDFExperience_JobTitleUDF",PROFILE.job_title1);tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-0-frm-dv_cs_experience_UDFExperience_Title",PROFILE.job_title1);
1==PROFILE.current_job1&&document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-0-frm:dv_cs_experience_CurrentEmployer")&&document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-0-frm:dv_cs_experience_CurrentEmployer").click();dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-0-frm-dv_cs_experience_BeginDate.month",PROFILE.job_start_month1-1);dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-0-frm-dv_cs_experience_BeginDate.year",
PROFILE.job_start_year1);dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-0-frm-dv_cs_experience_EndDate.month",PROFILE.job_end_month1-1);dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-0-frm-dv_cs_experience_EndDate.year",PROFILE.job_end_year1);""!=PROFILE.employer2&&(null==document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-1-frm-dv_cs_experience_Employer")&&(sessionStorage.setItem("reloading","true"),document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+
a+"-we-lblAddWorkExperience").click()),setTimeout(function(){document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-1-frm-dv_cs_experience_Employer").value=PROFILE.employer2;tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-1-frm-dv_cs_experience_Responsibility",PROFILE.job_desc2);tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-1-frm-dv_cs_experience_JobFunction",PROFILE.job_title2);tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-1-frm-dv_cs_experience_UDFExperience_JobTitleUDF",
PROFILE.job_title2);tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-1-frm-dv_cs_experience_UDFExperience_Title",PROFILE.job_title2);1==PROFILE.current_job2&&document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-1-frm:dv_cs_experience_CurrentEmployer")&&document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-1-frm:dv_cs_experience_CurrentEmployer").click();dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-1-frm-dv_cs_experience_BeginDate.month",
PROFILE.job_start_month2-1);dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-1-frm-dv_cs_experience_BeginDate.year",PROFILE.job_start_year2);dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-1-frm-dv_cs_experience_EndDate.month",PROFILE.job_end_month2-1);dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-1-frm-dv_cs_experience_EndDate.year",PROFILE.job_end_year2)},5E3));""!=PROFILE.employer3&&(document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+
a+"-we-lblAddWorkExperience").click(),setTimeout(function(){document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-0-frm-dv_cs_experience_Employer").value=PROFILE.employer3;tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-2-frm-dv_cs_experience_Responsibility",PROFILE.job_desc3);tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-2-frm-dv_cs_experience_JobFunction",PROFILE.job_title3);tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-2-frm-dv_cs_experience_UDFExperience_JobTitleUDF",
PROFILE.job_title3);tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-2-frm-dv_cs_experience_UDFExperience_Title",PROFILE.job_title3);1==PROFILE.current_job3&&document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-2-frm:dv_cs_experience_CurrentEmployer")&&document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-2-frm:dv_cs_experience_CurrentEmployer").click();dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-2-frm-dv_cs_experience_BeginDate.month",
PROFILE.job_start_month3-1);dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-2-frm-dv_cs_experience_BeginDate.year",PROFILE.job_start_year3);dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-2-frm-dv_cs_experience_EndDate.month",PROFILE.job_end_month3-1);dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+a+"-we-wei-2-frm-dv_cs_experience_EndDate.year",PROFILE.job_end_year3)},5E3));document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+b+"-csef-efi-0-frm-dv_cs_education_Institution")?
tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+b+"-csef-efi-0-frm-dv_cs_education_Institution",PROFILE.university):document.evaluate("//*[contains(text(), 'University')]//following::input[1]",document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).value=PROFILE.university;tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+b+"-csef-efi-0-frm-dv_cs_education_OtherInstitutionCity",PROFILE.uni_city);tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+b+"-csef-efi-0-frm-dv_cs_education_Program",
PROFILE.major);tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+b+"-csef-efi-0-frm-dv_cs_education_gpa",PROFILE.gpa);tryvalue("et-ef-content-ftf-gp-j_id_id16pc9-page_"+b+"-csef-efi-0-frm-dv_cs_education_gpaRange","4");var c=document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_"+b+"-csef-efi-0-frm-dv_cs_education_StudyLevel");c.value=document.evaluate('//*[@id="et-ef-content-ftf-gp-j_id_id16pc9-page_'+b+'-csef-efi-0-frm-dv_cs_education_StudyLevel"]//option[contains(text(), "'+PROFILE.degree+
'")]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).value;c.dispatchEvent(inputevent2);c.dispatchEvent(changeevent);dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+b+"-csef-efi-0-frm-dv_cs_education_startDate.month",PROFILE.uni_start_month-1);dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+b+"-csef-efi-0-frm-dv_cs_education_startDate.year",PROFILE.uni_start_year);dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+b+"-csef-efi-0-frm-dv_cs_education_graduationDate.month",
PROFILE.grad_month-1);dateselect("et-ef-content-ftf-gp-j_id_id16pc9-page_"+b+"-csef-efi-0-frm-dv_cs_education_graduationDate.year",PROFILE.grad_year);setTimeout(function(){taleoflag=!1;completeNotification()},3E3)}
function taleo(){if(document.getElementById("dialogTemplate-dialogForm-login-password"))return taleoLogin();if(existsxpath('//*[contains(text(), "New User Registration")]'))return taleoRegister();if(existsxpath('//*[contains(text(), "Security Question")]'))return taleoSecurity();if(document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_0-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_FirstName")||document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_1-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_FirstName")||
document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_2-cpi-cfrmsub-frm-dv_cs_candidate_personal_info_FirstName"))return taleoPersonalinfo();if(document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_0-we-wei-0-frm-dv_cs_experience_Employer")||document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_1-we-wei-0-frm-dv_cs_experience_Employer")||document.getElementById("et-ef-content-ftf-gp-j_id_id16pc9-page_2-we-wei-0-frm-dv_cs_experience_Employer"))return taleoExperience();
document.getElementById("et-ef-content-ftf-saveContinueCmdBottom")&&document.getElementById("et-ef-content-ftf-saveContinueCmdBottom");document.getElementById("editTemplateMultipart-editForm-content-ftf-saveContinueCmdBottom")&&document.getElementById("editTemplateMultipart-editForm-content-ftf-saveContinueCmdBottom")};function selectItem(a,b){var c=new Event("mousedown");document.evaluate(a,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).dispatchEvent(c);a=document.querySelector("#select2-drop > div > input");a.value=b;c=new Event("keyup-change");a.dispatchEvent(c);setTimeout(function(){var e=document.evaluate("//*[contains(text(), '"+b+"')]/ancestor::li",document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0),f=new Event("mousedown",{bubbles:!0,cancelable:!0}),h=new Event("mouseup",
{bubbles:!0,cancelable:!0});e.dispatchEvent(f);e.dispatchEvent(h)},1500)}function simplexpathtrytype(a,b){existsxpath(a)&&(document.evaluate(a,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).value=b)}
function greenhouse(){setTimeout(function(){trytype("input[id='first_name']",PROFILE.first_name);trytype("input[id='last_name']",PROFILE.last_name);trytype("input[id='email']",PROFILE.email);trytype("input[id='phone']",PROFILE.phone);trytype("input[aria-label='Education Start Month']",PROFILE.uni_start_month);trytype("input[aria-label='Education Start Year']",PROFILE.uni_start_year);trytype("input[aria-label='Education End Month']",PROFILE.grad_month);trytype("input[aria-label='Education End Year']",
PROFILE.grad_year);simplexpathtrytype('//*[contains(text(), "LinkedIn Profile")]//input[@type="text"]',PROFILE.linkedin);simplexpathtrytype('//*[contains(text(), "Github")]//input[@type="text"]',PROFILE.github);simplexpathtrytype('//*[contains(text(), "Website")]//input[@type="text"]',PROFILE.website);selectItem("//*[@id='s2id_education_degree_0']//a",PROFILE.degree);setTimeout(function(){selectItem("//*[@id='s2id_education_discipline_0']//a",PROFILE.major);setTimeout(function(){completeNotification()},
1200)},3E3)},1E3)};function lever(){document.getElementsByName("name")[0].value=PROFILE.first_name;document.getElementsByName("email")[0].value=PROFILE.email;document.getElementsByName("phone")[0].value=PROFILE.phone;1==PROFILE.current_job1?document.getElementsByName("org")[0].value=PROFILE.employer1:1==PROFILE.current_job2?document.getElementsByName("org")[0].value=PROFILE.employer2:1==PROFILE.current_job3&&(document.getElementsByName("org")[0].value=PROFILE.employer3);document.getElementsByName("urls[LinkedIn]")[0].value=
PROFILE.linkedin;document.getElementsByName("urls[GitHub]")[0].value=PROFILE.github;document.getElementsByName("urls[Portfolio]")[0].value=PROFILE.website;setTimeout(function(){completeNotification()},800)};
