var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.arrayFromIterator=function(a){for(var b,d=[];!(b=a.next()).done;)d.push(b.value);return d};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return a[b];d=a[d];return void 0!==d?d:a[b]};$jscomp.polyfill=function(a,b,d,c){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,d,c):$jscomp.polyfillUnisolated(a,b,d,c))};
$jscomp.polyfillUnisolated=function(a,b,d,c){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var k=a[c];if(!(k in d))return;d=d[k]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,d,c){var k=a.split(".");a=1===k.length;c=k[0];c=!a&&c in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var r=0;r<k.length-1;r++){var v=k[r];if(!(v in c))return;c=c[v]}k=k[k.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?c[k]:null;b=b(d);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,k,{configurable:!0,writable:!0,value:b}):b!==d&&(void 0===$jscomp.propertyToPolyfillSymbol[k]&&($jscomp.propertyToPolyfillSymbol[k]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(k):
$jscomp.POLYFILL_PREFIX+k),k=$jscomp.propertyToPolyfillSymbol[k],$jscomp.defineProperty(c,k,{configurable:!0,writable:!0,value:b})))};$jscomp.assign=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.assign?Object.assign:function(a,b){for(var d=1;d<arguments.length;d++){var c=arguments[d];if(c)for(var k in c)$jscomp.owns(c,k)&&(a[k]=c[k])}return a};$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");
$jscomp.polyfill("Object.is",function(a){return a?a:function(b,d){return b===d?0!==b||1/b===1/d:b!==b&&d!==d}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(b,d){var c=this;c instanceof String&&(c=String(c));var k=c.length;d=d||0;for(0>d&&(d=Math.max(d+k,0));d<k;d++){var r=c[d];if(r===b||Object.is(r,b))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,d){if(null==a)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(b,d){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,d||0)}},"es6","es3");
var PROFILE={first_name:"",last_name:"",email:"",phone:"",linkedin:"",website:"",github:"",street_address:"",city:"",state:"",zip_code:"",university:"",uni_city:"",gpa:4,major:"",degree:"",uni_start_month:8,uni_start_year:"2017",grad_month:9,grad_year:"2021",degree_received:1,employer1:"",job_title1:"",current_job1:0,job_location1:"",job_start_month1:8,job_start_year1:"",job_end_month1:3,job_end_year1:"",job_desc1:"",employer2:"",job_title2:"",current_job2:1,job_location2:"",job_start_month2:3,job_start_year2:"",
job_end_month2:4,job_end_year2:"",job_desc2:"",employer3:"",job_title3:"",current_job3:1,job_location3:"",job_start_month3:3,job_start_year3:"",job_end_month3:4,job_end_year3:"",job_desc3:"",username:"",password:"",question:"bagool",answer:"bafool"},FormPersistence=function(){function a(h,e){e=Object.assign({},{include:[],exclude:[],includeFilter:null,excludeFilter:null},e);var g={};h=$jscomp.makeIterator(h.elements);for(var f=h.next();!f.done;f=h.next()){f=f.value;var l=f.tagName,m=f.type;if(!(m=
"INPUT"===l&&"file"===m)&&!(m=d(f.name,e.include,e.exclude))){m=f;var q=e.includeFilter,n=e.excludeFilter;m=n&&n(m)||q&&!q(m)?!0:!1}if(!m)if("INPUT"===l)l=f.type,"radio"===l?f.checked&&b(g,f.name,f.value):"checkbox"===l?b(g,f.name,f.checked):b(g,f.name,f.value);else if("TEXTAREA"===l)b(g,f.name,f.value);else if("SELECT"===l)if(f.multiple)for(l=$jscomp.makeIterator(f.options),m=l.next();!m.done;m=l.next())m=m.value,m.selected&&b(g,f.name,m.value);else b(g,f.name,f.value)}return g}function b(h,e,g){e in
h||(h[e]=[]);h[e].push(g)}function d(h,e,g){return!h||g.includes(h)||0<e.length&&!e.includes(h)?!0:!1}function c(h,e){e=Object.assign({},{uuid:null,useSessionStorage:!1},e);var g=a(h,e);(e.useSessionStorage?sessionStorage:localStorage).setItem(w(h,e.uuid),JSON.stringify(g))}function k(h,e,g){var f=Object.assign({},{valueFunctions:null,include:[],exclude:[],includeFilter:null,excludeFilter:null},g);g=[];null!==f.valueFunctions&&(g=x(e,h,f));var l={},m;for(m in e)l.$jscomp$loop$prop$name$7=m,d(l.$jscomp$loop$prop$name$7,
f.include,f.exclude)||g.includes(l.$jscomp$loop$prop$name$7)||[].concat($jscomp.arrayFromIterable(h.elements)).filter(function(q){return function(n){var p;if(p=n.name===q.$jscomp$loop$prop$name$7){p=f.includeFilter;var t=f.excludeFilter;p=!(t&&t(n)||p&&!p(n))}return p}}(l)).forEach(function(q){return function(n,p){var t=e[q.$jscomp$loop$prop$name$7],u=n.tagName;if("INPUT"===u)u=n.type,"radio"===u?n.checked=n.value===t[0]:"checkbox"===u?n.checked=t[p]:n.value=t[p];else if("TEXTAREA"===u)n.value=t[p];
else if("SELECT"===u)if(n.multiple)for(n=$jscomp.makeIterator(n.options),p=n.next();!p.done;p=n.next())p=p.value,p.selected=t.includes(p.value);else n.value=t[p]}}(l)),l={$jscomp$loop$prop$name$7:l.$jscomp$loop$prop$name$7}}function r(h,e){var g=Object.assign({},{uuid:null,useSessionStorage:!1},e);if(g=(g.useSessionStorage?sessionStorage:localStorage).getItem(w(h,g.uuid)))g=JSON.parse(g),k(h,g,e)}function v(h,e){e=Object.assign({},{uuid:null,useSessionStorage:!1},e);(e.useSessionStorage?sessionStorage:
localStorage).removeItem(w(h,e.uuid))}function x(h,e,g){var f=[],l;for(l in g.valueFunctions)if(l in h&&!d(l,g.include,g.exclude)){for(var m=$jscomp.makeIterator(h[l]),q=m.next();!q.done;q=m.next())g.valueFunctions[l](e,q.value);f.push(l)}return f}function w(h,e){if(!e&&!h.id)throw Error("form persistence requires a form id or uuid");return"form#"+(e?e:h.id)}return{persist:function(h,e){var g=Object.assign({},{saveOnSubmit:!1},e);r(h,g);var f=function(){return c(h,g)},l=function(){window.removeEventListener("unload",
f);f()};window.addEventListener("beforeunload",l);window.addEventListener("unload",f);g.saveOnSubmit||h.addEventListener("submit",function(){window.removeEventListener("beforeunload",l);window.removeEventListener("unload",f);v(h,g)})},load:r,save:c,clearStorage:v,serialize:a,deserialize:k}}();(function(){"undefined"!==typeof module&&module.exports&&(module.exports=exports=FormPersistence)})();
window.addEventListener("load",function(){function a(){PROFILE.first_name=document.getElementById("fname").value;PROFILE.last_name=document.getElementById("lname").value;PROFILE.email=document.getElementById("email").value;PROFILE.phone=document.getElementById("phone").value;PROFILE.linkedin=document.getElementById("linkedin").value;PROFILE.website=document.getElementById("website").value;PROFILE.github=document.getElementById("github").value;PROFILE.street_address=document.getElementById("street_address").value;
PROFILE.city=document.getElementById("city").value;PROFILE.state=document.getElementById("selectstate").value;PROFILE.zip_code=document.getElementById("zip_code").value;PROFILE.university=document.getElementById("university").value;PROFILE.uni_city=document.getElementById("uni_city").value;PROFILE.gpa=document.getElementById("gpa").value;PROFILE.degree=document.getElementById("selectdegree").value;PROFILE.major=document.getElementById("major").value;var c=document.getElementById("uni_start").value.split("-");
PROFILE.uni_start_month=parseInt(c[1]);PROFILE.uni_start_year=c[0];c=document.getElementById("grad_date").value.split("-");PROFILE.grad_month=parseInt(c[1]);PROFILE.grad_year=c[0];PROFILE.employer1=document.getElementById("employer1").value;PROFILE.job_title1=document.getElementById("job_title1").value;PROFILE.current_job1=document.getElementById("current_job1").checked;PROFILE.job_location1=document.getElementById("job_location1").value;c=document.getElementById("job_start1").value.split("-");PROFILE.job_start_month1=
parseInt(c[1]);PROFILE.job_start_year1=c[0];c=document.getElementById("job_end1").value.split("-");PROFILE.job_end_month1=parseInt(c[1]);PROFILE.job_end_year1=c[0];PROFILE.job_desc1=document.getElementById("job_desc1").value;PROFILE.employer2=document.getElementById("employer2").value;PROFILE.job_title2=document.getElementById("job_title2").value;PROFILE.current_job2=document.getElementById("current_job2").checked;PROFILE.job_location2=document.getElementById("job_location2").value;c=document.getElementById("job_start2").value.split("-");
PROFILE.job_start_month2=parseInt(c[1]);PROFILE.job_start_year2=c[0];c=document.getElementById("job_end2").value.split("-");PROFILE.job_end_month2=parseInt(c[1]);PROFILE.job_end_year2=c[0];PROFILE.job_desc2=document.getElementById("job_desc2").value;PROFILE.employer3=document.getElementById("employer3").value;PROFILE.job_title3=document.getElementById("job_title3").value;PROFILE.current_job3=document.getElementById("current_job3").checked;PROFILE.job_location3=document.getElementById("job_location3").value;
c=document.getElementById("job_start3").value.split("-");PROFILE.job_start_month3=parseInt(c[1]);PROFILE.job_start_year3=c[0];c=document.getElementById("job_end3").value.split("-");PROFILE.job_end_month3=parseInt(c[1]);PROFILE.job_end_year3=c[0];PROFILE.job_desc3=document.getElementById("job_desc3").value;PROFILE.username=document.getElementById("username").value;PROFILE.password=document.getElementById("password").value;PROFILE.question=document.getElementById("question").value;PROFILE.answer=document.getElementById("answer").value;
c=JSON.stringify(PROFILE);chrome.storage.local.set({profile:c},function(){document.getElementById("successMessage").style.visibility="visible";chrome.storage.local.get("profile",function(k){PROFILE=JSON.parse(k.profile)})})}var b=document.getElementById("submit"),d=document.getElementById("profile");FormPersistence.persist(d);b&&(b.onclick=function(){a()})});var _gaq=_gaq||[];_gaq.push(["_setAccount","UA-188515357-1"]);_gaq.push(["_trackPageview"]);
(function(){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src="https://ssl.google-analytics.com/ga.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})();
